# Generated by Django 4.2.20 on 2025-03-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='spot_numer',
            new_name='spot_number',
        ),
    ]
